# Generated by Django 2.1.10 on 2019-07-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0007_make_order_provider_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringorder',
            name='invoicing_data',
            field=models.TextField(max_length=1250, verbose_name='Invoicing data'),
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='message',
            field=models.TextField(blank=True, max_length=1250, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='cateringproduct',
            name='description',
            field=models.TextField(blank=True, max_length=1250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cateringproduct',
            name='description_en',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cateringproduct',
            name='description_fi',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cateringproduct',
            name='description_sv',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
    ]
