# Generated by Django 2.1.10 on 2019-07-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0079_reservation_extra_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of modification'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of modification'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='order_text',
            field=models.CharField(default='0', max_length=200, verbose_name='Järjestys'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event_description',
            field=models.TextField(blank=True, max_length=1250, verbose_name='Event description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_extra_questions',
            field=models.TextField(blank=True, max_length=1250, verbose_name='Reservation extra questions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_en',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_fi',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_sv',
            field=models.TextField(blank=True, max_length=1250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of modification'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Resource', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption',
            field=models.CharField(default='kuva', max_length=100, verbose_name='Caption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption',
            field=models.CharField(default='kuva', max_length=200, verbose_name='Picture caption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of modification'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Unit', verbose_name='Resource'),
        ),
    ]
