# Generated by Django 2.1.10 on 2019-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0081_auto_20190710_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='caption',
            field=models.CharField(max_length=100, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption',
            field=models.CharField(max_length=200, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='picture_caption_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Picture caption'),
        ),
    ]
