# Generated by Django 2.1.10 on 2019-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0082_auto_20190710_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_fi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='resourceimage',
            name='caption_sv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption'),
        ),
    ]
